### ISSUE TITLE
edits to Visioneval.org

### ISSUE THREAD

**Issue by mrspeel** [VisionEval/VisionEval#1]
On this page, the "Future Builder" viewer is no longer supported.  Suggest dropping this section.
Does ARC have a viewer?
http://visioneval.org/interactive/2019/01/01/1-viewers.html

Some edits for"Current Status" of this page:
https://visioneval.org/users/2018/01/01/4-greenstep.html
GreenSTEP continues to be used as a State-wide planning tool by ODOT, as they transition to VisionEval tools.  GreenSTEP is not available on a public repository currently. .....

The models developed from GreenSTEP form the core of all VisionEval models. Following the successful transfer of RSPM and RPAT to the VisionEval project, a pilot statewide VisionEval model has also been transferred to the framework, as an extension of RSPM. This effort was led by Oregon DOT (and Maryland DOT) , via a contract led by CH2M Hill with sub-consultants RSG, Inc. and the original GreenSTEP author of Oregon Systems Analytics. It is currently being tested.  This should greatly facilitate transferring EERPAT to VisionEval.

also need to update "Current Status" of this page:
https://visioneval.org/users/2018/01/01/3-rspm.html

This page could use some hyperlinks to the referenced wiki pages, plus replace last bullet with actual Documentation plan (completed March 2018), and pilot VE-State (completed March 2019): 
https://visioneval.org/users/2018/01/01/1-ongoing.html

Looks Great! Thanks for all this work!

**Comment by shichenfan** [comment]
ARC's viewer is still being modified. It supposed to be ready at end of May.

**Comment by dflynn-volpe** [comment]
@mrspeel, thanks! -- see [changes made over here](https://github.com/VisionEval/visioneval.github.io/commit/23759d966e7783c993a5e5c41493736ab8b53b4d). For other website issues, it's a little better to directly put them in the website repo: https://github.com/VisionEval/visioneval.github.io/issues. 

@shichenfan Please keep us updated about the ARC viewer, thanks

**Comment by mrspeel** [comment]
@dflynn-volpe -- Thanks!  One more...
Can you add the PSU multi-modal model reference as a hyper link to the 2nd bullet on this page? 
https://visioneval.org/users/2018/01/01/1-ongoing.html

Possible link to this (first 2 from contributor review team, last is actual ODOT Research report):
https://cities-lab.github.io/VETravelDemandMM/Overview_slides.html#1 
https://cities-lab.github.io/VETravelDemandMM/Intro.html
https://www.oregon.gov/ODOT/Programs/ResearchDocuments/SPR788RSPMTool.pdf
