### ISSUE TITLE
install.R file refers to gregorbj/visioneval repo

### ISSUE THREAD

**Issue by gregorbj** [VisionEval/VisionEval#2]
The install.R script in the top level of the repo identifies in line 9 that the repo to install from is gregorbj/visioneval
     repo <- "gregorbj/visioneval/"          #repository
This needs to be changed to the visioneval/visioneval repo.
Also, it might be better to have this in a separate directory such as 'install' along with a readme which includes instructions for the different ways for installing. I think the user might try to install with this script rather than read the wiki on installation.

**Comment by jrawbits** [comment]
Install.R is going away in the immediate next version of VisionEval in favor of the VE-Installer (which requires a certain setup in advance - specifically R Tools and Git for Windows or a comparable Linux environment).

Once we've beta-tested the installer plus VisionEval combination, we'll make VE-Installer and official sub-module of VisionEval, so you'll get an (empty) "install" folder that you can initialize with "git submodule init" or cloning with a corresponding flag.  I want these to stay as separate projects as they will move at different speeds with different developers.

In addition to the empty submodule folder, I'll also include a document called 'Installing' which has instructions for pulling down the submodule, summarizes the setup procedures, and then directs to "install/ReadMe.md" (in the submodule) for the gory details.

All of this will appear first on VisionEval-dev (in "development" then "master") and move to the master VisionEval repository when we do a formal release (when it's all working and stable, and ideally ahead of the TRB Planning Applications conference 2019).

**Comment by jrawbits** [comment]
Personally, apart from the development environment (which you need anyway to do the clone step for Install.R, and probably the build steps with RTools), I think the VE-Installer is much easier for a developer and more thorough (less room to let local R library history contaminate the environment, able to run module tests locally, able to build consistently on any version of R with corresponding BioConductor, etc.).  YMMV, which is why there will be a beta test period :-)

**Comment by gregorbj** [comment]
I think the installer is the right way to go and then eliminate the install.R script. We do, however, need the ability for a developer or user to add a package to the ve-lib folder that the installer creates. For example, I'm doing work for ODOT that will require adding several powertrains and fuels packages, a utilities package for extracting data from datastore, and a bug fix to visioneval. I'll be developing an approach to do this and will share.

**Comment by jrawbits** [comment]
We already have that in the pipeline.  The new VE Installer (see the "development" branch at [github.com:/jrawbits/VE-Installer](https://github.com/jrawbits/VE-installer.git) lets you configure multiple "roots" for VisionEval.  So in the scenario Brian just described, you have the option of picking packages from "VisionEval A" and "VisionEval B" and merging them into a single working runtime.  "VisionEval B" (for example) does not have to be a complete version - it could just have the new powertrains and fuels, the utility package or whatever.  You run the installer, it picks the packages and model scripts you asked for, and generates a single consistent runtime).  So what the installer creates is entirely configurable, allowing you to pull together old, new or anything in between.

**Comment by gregorbj** [comment]
Sounds good. Looking forward to it.

**Comment by jrawbits** [comment]
The VE Installer is now up and running.  Please place installation issues on the VisionEval/VE-Installer repository.  Closing this as it is no longer relevant.
